magaze/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("shop.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import product_detail, product_list

app_name = "shop"
urlpatterns = [
    path('',product_list,name='product_list'),
    path('category/<slug:category_slug>/', product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", product_detail, name="product_detail"),
]

shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    
    name= models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["name"])
        ]
        verbose_name = "категория"
        verbose_name_plural = "категория"
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category",
        args=[self.slug])
        
class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name="product",
        on_delete=models.PROTECT
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(
        upload_to="products/%d/%m/%Y",
        blank=True
    )
    dascription = models.TextField(blank=True)
    price = models.DecimalField(
        max_digits = 10,
        decimal_places = 2 ,
    )
    available=models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updates = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ["name"]
        verbose_name = "товар"
        verbose_name_plural = "товары"
        indexes = [
            models.Index(fields=["id","slug"]),
            models.Index(fields=["name"]),
            models.Index(fields=["-created"]),
        ]
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("shop:product_detail",
        args=[self.id,self.slug])
        

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,"list_stop.html",{
        "category": category,
        "categories": categories,
        "products": products
    })
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(request, "detail.html",{
        "product": product
    })

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} My shop {% endblock %}</title>
    <link  href="{% static 'css/base.css' %}"rel="stylesheet">
</head>
<body>
<div id="header">
    <a href="/" class="logo">My shop</a>
</div>  
<div id="subheader">
    <div class="cart">
        {% with total_items=cart|length %}
            {% if total_items > 0 %}
            В вашей корзине:
            <a href="{% url "cart:cart_detail" %}">
            {{ total_items }} тов. Сумма:
             {{ cart.get_total }} сом
            </a>
            {% else %}
             ваша корзина пуста
            {% endif %}
        {% endwith %}
    </div>
</div>
<div id="content">
    {% block content %} {% endblock %}
</div>
</body>
</html>

templates/detail.html
{% extends "base.html" %}
{% block content %}
<h1> {{ product.name }}</h1>
<p>{{ product.description }}</p>
{% if product.image %}
<img src="{{ product.image.url }}" alt="">
{% else %}
<p>Изображение отсутствует</p>
{% endif %}
<p>Цена: {{ product.price}} $</p>
{% endblock %}

templates/list_stop.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1>Категории</h1>
<ul>
    <li><a href="{% url 'shop:product_list' %} ">Все</a></li>
    {% for c in categories %}
    <li>
        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
    </li>
    {% endfor %}
</ul>
<h2>Товары</h2>
<ul>
    {% for product in products %}
    <li> <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
    - {{product.price }} $
    </li>
    {% endfor %}
</ul>
{% endblock %}